-- Database: prim

-- DROP DATABASE IF EXISTS prim;

DROP DATABASE IF EXISTS prim;

CREATE DATABASE prim
    WITH
    OWNER = prim
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;