FROM --platform=linux/aarch64 ubuntu:22.04
RUN apt-get update && apt-get install -y netcat-openbsd

WORKDIR /prim
COPY ./cert /prim/cert
COPY ./msglog /prim/msglog
COPY ./target/aarch64-unknown-linux-gnu/release/msglogger /prim/msglogger_main

CMD ./msglogger_main