FROM --platform=linux/aarch64 ubuntu:22.04
RUN apt-get update && apt-get install -y netcat-openbsd

WORKDIR /prim
COPY ./cert /prim/cert
COPY ./scheduler/config-quickstart.toml /prim/config.toml
COPY ./target/aarch64-unknown-linux-gnu/release/scheduler /prim/scheduler_main
EXPOSE 11220 11222 11320

CMD ./scheduler_main --config=config.toml --my_id=524289