FROM alpine
WORKDIR /prim
COPY ./cert /prim/cert
COPY ./recorder/config-quickstart.toml /prim/config.toml
COPY ./target/x86_64-unknown-linux-musl/release/api /prim/api
EXPOSE 11150 11151 11250

CMD ls -a
CMD ./api --config=config.toml --my_id=1