FROM alpine
WORKDIR /prim
COPY ./cert /prim/cert
COPY ./scheduler/config-quickstart.toml /prim/config.toml
COPY ./target/x86_64-unknown-linux-musl/release/scheduler /prim/scheduler
EXPOSE 11150 11151 11250

CMD ./scheduler --config=config.toml --my_id=1