FROM alpine
WORKDIR /prim
COPY ./cert /prim/cert
COPY ./recorder/config-quickstart.toml /prim/config.toml
COPY ./target/x86_64-unknown-linux-musl/release/recorder /prim/recorder
EXPOSE 11140

CMD ./recorder --config=config.toml --my_id=1