FROM --platform=linux/amd64 ubuntu:22.04
WORKDIR /prim
COPY ./cert /prim/cert
COPY ./message/config-quickstart.toml /prim/config.toml
COPY ./target/x86_64-unknown-linux-gnu/release/message /prim/message
COPY ./target/x86_64-unknown-linux-gnu/release/msglogger /prim/msglogger
EXPOSE 11120 11122

CMD ./msglogger -daemon && ./message --config=config.toml --my_id=1