FROM --platform=linux/amd64 ubuntu:22.04
RUN apt-get update && apt-get install -y netcat-openbsd

WORKDIR /prim
COPY ./cert /prim/cert
COPY ./seqnum/config-quickstart.toml /prim/config.toml
COPY ./target/x86_64-unknown-linux-gnu/release/seqnum /prim/seqnum_main
EXPOSE 11420

CMD ./seqnum_main --config=config.toml --my_id=1048577