FROM --platform=linux/amd64 ubuntu:22.04
WORKDIR /prim

COPY ./cert /prim/cert
COPY ./api/config-quickstart.toml /prim/config.toml
COPY ./target/x86_64-unknown-linux-gnu/release/api /prim/api
EXPOSE 11320 11330

CMD ./api --config=config.toml