FROM --platform=linux/amd64 ubuntu:22.04
WORKDIR /prim
COPY ./cert /prim/cert
COPY ./scheduler/config-quickstart.toml /prim/config.toml
COPY ./target/x86_64-unknown-linux-gnu/release/scheduler /prim/scheduler
EXPOSE 11220 11222 11320

CMD ./scheduler --config=config.toml --my_id=524289